### PR TITLE
Fixes for Mykloudz Github Issue No. 18 & 16

### PR DESCRIPTION
**Pull request by mykloudz**
https://github.com/metasfresh/metasfresh/issues/5358

### CODE REVIEW

**Comment by metas-ts** [comment]
hi @mykloudz ,
thx a lot for this PR!
Please let us know what the fix is about. Also note that the PR currently can't be build by our CI: https://jenkins.metasfresh.com/job/metasfresh-webui/job/PR-1222/2/console
Maybe you need to update your forg with our latest `master`

**Comment by mykloudz** [comment]
Hi @metas-ts,

The fixes contains solution for the below issues:
1. In the Handling Unit Editor Picking screen when we input a keyword, the results should not include already picked item details.
2. Also in the same screen while displaying the results, it should validate attributes of Sales Order with that of Handling Unit line item we are trying to pick and only results with matching attributes should be shown.

And we suspect the build failure is due to the dependency of Metasfresh-Webui-Api PR on Metasfresh PR. So we request you to merge the PR from metasfresh repo first.. which doesn't have any dependency.

**Comment by metasnw** [comment]
@mykloudz I guess you are referring to this PR ?
https://github.com/metasfresh/metasfresh/pull/5356

**Comment by mykloudz** [comment]
Hi @metasnw we have updated our fork just few hours back.

@metas-ts could you please merge the PRs?

**Comment by roopesh-kh** [comment]
> 
> 
> @mykloudz I guess you are referring to this PR ?
> [metasfresh/metasfresh#5356](https://github.com/metasfresh/metasfresh/pull/5356)

Hi @metasnw , that's right. This PR depends on some changes made in PR 5356.
Can you please help by merging both the PRs.

**Pull request closed without merging**
